# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 086a70fe3554b496df554fec9be0e05302330a875435749d62e5463a316493019d99ec3cc5ca1802b25c0e55be40ffcf8010967f23b62d807fae7b8f92d27e37

test:
  secret_key_base: 7fa880765a62202c61c2587a37b58bd25b6d24d97d1c7de613bfcfc9762579cc4141335a66efc00b8df3e7298ccc2821a47b58aaf51550ca1e8a93d2113ba12c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
